env:
  TZ: "Asia/Jakarta"
  ENV: "dev"
  server:
    SERVER_PORT: "8000"
    SERVER_NAME: "pari"
  log:
    LOG_DIRECTORY: "var/log/filebeat"
  db:
    DB_HOST: "localhost"
    DB_PORT: "5433"
    DB_USER: "postgres"
    DB_NAME: "pari"
    DB_PASSWORD: "katasandi12"